import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

class ApiServerConfig {
  const ApiServerConfig({
    required this.name,
    required this.url,
    this.environment = 'development',
    this.readOnly = false,
    this.confirmMutations = false,
  });

  final String name;
  final String url;
  final String environment;
  final bool readOnly;
  final bool confirmMutations;

  bool get isProduction => environment.toLowerCase() == 'production';

  Map<String, dynamic> toOpenApi() => {
    'url': url,
    'description': name,
    'x-name': name,
    'x-environment': environment,
    'x-read-only': readOnly,
    'x-confirm-mutations': confirmMutations,
  };
}

class FroggyConfig {
  const FroggyConfig({
    this.title = 'FroggyDocs Generated API',
    this.version = '1.0.0',
    this.description = 'Auto-generated by FroggyDocs',
    this.basePath = '/',
    this.outputDirectory = 'dist',
    this.defaultEnvironment = '',
    this.specOutput = 'frontend/web/froggy_docs.json',
    this.port = 8080,
    this.proxyUrl = '',
    this.specPath = '',
    this.specUrl = '',
    this.specHeaderEnvironment = '',
    this.specPollIntervalSeconds = 10,
    this.servers = const [],
  });

  final String title;
  final String version;
  final String description;
  final String basePath;
  final String outputDirectory;
  final String defaultEnvironment;
  final String specOutput;
  final int port;
  final String proxyUrl;
  final String specPath;
  final String specUrl;
  final String specHeaderEnvironment;
  final int specPollIntervalSeconds;
  final List<ApiServerConfig> servers;

  static FroggyConfig load([String directory = '.']) {
    final yamlFile = ['froggy_docs.yaml', 'froggy_docs.yml']
        .map((name) => File(p.join(directory, name)))
        .where((file) => file.existsSync())
        .firstOrNull;
    if (yamlFile != null) {
      final value = _toPlainValue(loadYaml(yamlFile.readAsStringSync()));
      if (value is! Map<String, dynamic>) {
        throw const FormatException('froggy_docs.yaml must contain a map');
      }
      return FroggyConfig.fromMap(value);
    }

    final legacyFile = File(p.join(directory, '.froggyrc'));
    if (legacyFile.existsSync()) {
      final value = jsonDecode(legacyFile.readAsStringSync());
      if (value is! Map<String, dynamic>) {
        throw const FormatException('.froggyrc must contain a JSON object');
      }
      return FroggyConfig.fromMap(value);
    }
    return const FroggyConfig();
  }

  factory FroggyConfig.fromMap(Map<String, dynamic> map) {
    final project = _stringMap(map['project']);
    final docs = _stringMap(map['docs']);
    final server = _stringMap(map['server']);
    final output = _stringMap(map['output']);
    final input = _stringMap(map['input']);
    final rawServers = map['servers'];
    final servers = <ApiServerConfig>[];
    if (rawServers is List) {
      for (final value in rawServers) {
        final item = _stringMap(value);
        final url = item['url']?.toString().trim() ?? '';
        if (url.isEmpty) continue;
        final environment = item['environment']?.toString() ?? 'development';
        servers.add(
          ApiServerConfig(
            name: item['name']?.toString() ?? environment,
            url: url,
            environment: environment,
            readOnly: item['readOnly'] == true,
            confirmMutations:
                item['confirmMutations'] == true ||
                environment.toLowerCase() == 'production',
          ),
        );
      }
    }

    final legacyProxy = server['proxy']?.toString() ?? '';
    if (servers.isEmpty && legacyProxy.isNotEmpty) {
      servers.add(ApiServerConfig(name: 'Local', url: legacyProxy));
    }

    return FroggyConfig(
      title: project['title']?.toString() ?? 'FroggyDocs Generated API',
      version: project['version']?.toString() ?? '1.0.0',
      description:
          project['description']?.toString() ?? 'Auto-generated by FroggyDocs',
      basePath: _normalizeBasePath(docs['basePath']?.toString() ?? '/'),
      outputDirectory: docs['outputDirectory']?.toString() ?? 'dist',
      defaultEnvironment: docs['defaultEnvironment']?.toString() ?? '',
      specOutput: output['file']?.toString() ?? 'frontend/web/froggy_docs.json',
      port: _intValue(server['port'], 8080),
      proxyUrl: legacyProxy,
      specPath: input['spec']?.toString() ?? '',
      specUrl: input['specUrl']?.toString() ?? '',
      specHeaderEnvironment: input['specHeaderEnv']?.toString() ?? '',
      specPollIntervalSeconds: _intValue(input['pollIntervalSeconds'], 10),
      servers: servers,
    );
  }

  Map<String, dynamic> get runtimeExtension => {
    'basePath': basePath,
    'defaultEnvironment': defaultEnvironment,
  };
}

Map<String, dynamic> _stringMap(dynamic value) {
  if (value is Map) {
    return value.map((key, item) => MapEntry(key.toString(), item));
  }
  return <String, dynamic>{};
}

dynamic _toPlainValue(dynamic value) {
  if (value is YamlMap || value is Map) {
    return Map<String, dynamic>.fromEntries(
      (value as Map).entries.map(
        (entry) => MapEntry(entry.key.toString(), _toPlainValue(entry.value)),
      ),
    );
  }
  if (value is YamlList || value is List) {
    return (value as List).map(_toPlainValue).toList();
  }
  return value;
}

int _intValue(dynamic value, int fallback) {
  if (value is int) return value;
  return int.tryParse(value?.toString() ?? '') ?? fallback;
}

String _normalizeBasePath(String value) {
  final trimmed = value.trim();
  if (trimmed.isEmpty || trimmed == '/') return '/';
  return '/${trimmed.replaceAll(RegExp(r'^/+|/+$'), '')}/';
}
