import 'dart:io';
import 'dart:convert';
import 'package:path/path.dart' as p;

class ParserEngine {
  static final Map<String, Map<String, dynamic>> _fileRegistry = {};

  static const Set<String> supportedExtensions = {
    '.dart',
    '.js',
    '.ts',
    '.jsx',
    '.tsx',
    '.py',
    '.go',
    '.rs',
    '.java',
    '.kt',
    '.scala',
    '.php',
    '.rb',
    '.cs',
    '.c',
    '.cpp',
    '.h',
    '.hpp',
  };

  static const Set<String> validMethods = {
    'get',
    'post',
    'put',
    'patch',
    'delete',
    'head',
    'options',
  };

  final Map<String, dynamic> _baseSpec = {
    "openapi": "3.0.0",
    "info": {
      "title": "FroggyDocs Generated API",
      "version": "1.0.0",
      "description": "Auto-generated by FroggyDocs",
    },
    "paths": {},
    "components": {
      "securitySchemes": {
        "bearerAuth": {
          "type": "http",
          "scheme": "bearer",
          "bearerFormat": "JWT",
        },
      },
    },
  };

  final List<String> _errors = [];
  final Set<String> _tags = {};

  String _getCommentPrefix(String filePath) {
    final ext = p.extension(filePath).toLowerCase();
    return switch (ext) {
      '.dart' => '//',
      '.js' || '.jsx' || '.ts' || '.tsx' => '//',
      '.py' || '.rb' => '#',
      '.go' ||
      '.rs' ||
      '.c' ||
      '.cpp' ||
      '.h' ||
      '.hpp' ||
      '.java' ||
      '.kt' ||
      '.scala' ||
      '.cs' => '//',
      '.php' => '//',
      _ => '//',
    };
  }

  bool _isCommentLine(String line, String prefix) {
    if (prefix == '//') {
      return line.trimLeft().startsWith('//');
    } else if (prefix == '#') {
      return line.trimLeft().startsWith('#');
    }
    return line.trimLeft().startsWith(prefix);
  }

  String _extractCommentText(String line, String prefix) {
    if (prefix == '//') {
      return line.replaceFirst(RegExp(r'^//\s*'), '').trim();
    } else if (prefix == '#') {
      return line.replaceFirst(RegExp(r'^#\s*'), '').trim();
    }
    return line.replaceFirst(RegExp(r'^$prefix\s*'), '').trim();
  }

  void removeFile(String filePath) {
    if (_fileRegistry.containsKey(filePath)) {
      _fileRegistry.remove(filePath);
      _generateSwaggerFile();
    }
  }

  void parseFile(String filePath) {
    _errors.clear();

    if (filePath.contains('frontend/') || filePath.contains('.dart_tool')) {
      return;
    }

    final file = File(filePath);
    if (!file.existsSync()) {
      removeFile(filePath);
      return;
    }

    final ext = p.extension(filePath).toLowerCase();
    if (!supportedExtensions.contains(ext)) {
      return;
    }

    final lines = file.readAsLinesSync();
    final commentPrefix = _getCommentPrefix(filePath);
    Map<String, dynamic> fileEndpoints = {};

    String? currentMethod;
    String? currentPath;
    String description = '';
    bool hasAuth = false;
    List<String> currentTags = [];
    List<Map<String, String>> requestBodyFields = [];
    bool isReadingBodyJson = false;
    StringBuffer bodyJsonBuffer = StringBuffer();
    int lineNumber = 0;

    String inferType(dynamic value) {
      if (value is String) return 'string';
      if (value is num) return 'number';
      if (value is bool) return 'boolean';
      if (value is List) return 'array';
      if (value is Map) return 'object';
      return 'string';
    }

    void flushEndpoint() {
      if (currentMethod != null) {
        if (currentPath == null) {
          _errors.add('Endpoint defined without path at line $lineNumber');
          currentMethod = null;
          currentPath = null;
          description = '';
          hasAuth = false;
          requestBodyFields.clear();
          bodyJsonBuffer.clear();
          return;
        }

        if (!validMethods.contains(currentMethod!.toLowerCase())) {
          _errors.add(
            'Invalid HTTP method "$currentMethod" at line $lineNumber',
          );
          currentMethod = null;
          currentPath = null;
          description = '';
          hasAuth = false;
          requestBodyFields.clear();
          bodyJsonBuffer.clear();
          return;
        }

        final path = currentPath!;
        final method = currentMethod!.toLowerCase();

        if (fileEndpoints[path] == null) {
          fileEndpoints[path] = {};
        }

        Map<String, dynamic> endpointData = {
          "summary": description.isNotEmpty ? description : "No description",
          "responses": {
            "200": {"description": "Successful response"},
          },
        };

        if (currentTags.isNotEmpty) {
          endpointData['tags'] = currentTags.toList();
        }

        if (hasAuth) {
          endpointData['security'] = [
            {"bearerAuth": []},
          ];
        }

        if (requestBodyFields.isNotEmpty) {
          Map<String, dynamic> properties = {};
          for (var field in requestBodyFields) {
            final fieldName = field['name'];
            if (fieldName != null && fieldName.isNotEmpty) {
              properties[fieldName] = {
                "type": (field['type'] ?? 'string').toString().toLowerCase(),
                "description": field['desc'] ?? '',
              };
            }
          }

          endpointData['requestBody'] = {
            "content": {
              "application/json": {
                "schema": {"type": "object", "properties": properties},
              },
            },
          };
        }

        fileEndpoints[path][method] = endpointData;
      }

      currentMethod = null;
      currentPath = null;
      description = '';
      hasAuth = false;
      currentTags.clear();
      requestBodyFields.clear();
      bodyJsonBuffer.clear();
    }

    for (final l in lines) {
      lineNumber++;
      final trimmed = l.trim();

      if (isReadingBodyJson) {
        if (!_isCommentLine(trimmed, commentPrefix)) {
          isReadingBodyJson = false;
          if (bodyJsonBuffer.isNotEmpty) {
            try {
              final jsonData = jsonDecode(bodyJsonBuffer.toString());
              if (jsonData is Map) {
                for (final entry in jsonData.entries) {
                  requestBodyFields.add({
                    'name': entry.key.toString(),
                    'type': inferType(entry.value),
                    'desc': 'Inferred from JSON',
                  });
                }
              }
            } catch (e) {
              _errors.add('Invalid JSON at line $lineNumber: $e');
            }
          }
          bodyJsonBuffer.clear();
        } else {
          final commentText = _extractCommentText(trimmed, commentPrefix);
          bodyJsonBuffer.write(commentText);
          continue;
        }
      }

      if (!_isCommentLine(trimmed, commentPrefix)) {
        if (trimmed.isNotEmpty) {
          flushEndpoint();
        }
        continue;
      }

      final commentText = _extractCommentText(trimmed, commentPrefix);
      if (!commentText.startsWith('@')) {
        continue;
      }

      final parts = commentText.split(RegExp(r'\s+'));
      if (parts.isEmpty) continue;

      final tag = parts[0];

      if (tag == '@api') {
        flushEndpoint();
        if (parts.length >= 3) {
          currentMethod = parts[1].toUpperCase();
          currentPath = parts[2];
        } else {
          _errors.add('@api requires method and path at line $lineNumber');
        }
      } else if (tag == '@desc') {
        description = commentText.replaceFirst('@desc', '').trim();
      } else if (tag == '@auth') {
        hasAuth = true;
      } else if (tag == '@tag') {
        if (parts.length >= 2) {
          final tagName = parts.sublist(1).join(' ');
          if (!_tags.contains(tagName)) {
            _tags.add(tagName);
          }
          if (!currentTags.contains(tagName)) {
            currentTags.add(tagName);
          }
        }
      } else if (tag == '@body') {
        if (parts.length >= 3) {
          final fieldName = parts[1];
          final fieldType = parts[2];
          final fieldDesc = parts.length > 3 ? parts.sublist(3).join(' ') : '';
          requestBodyFields.add({
            'name': fieldName,
            'type': fieldType,
            'desc': fieldDesc,
          });
        } else {
          _errors.add('@body requires field name and type at line $lineNumber');
        }
      } else if (tag == '@body-file') {
        if (parts.length >= 2) {
          final jsonFile = File(p.join(p.dirname(filePath), parts[1]));
          if (jsonFile.existsSync()) {
            try {
              final jsonData = jsonDecode(jsonFile.readAsStringSync());
              if (jsonData is Map) {
                for (final entry in jsonData.entries) {
                  requestBodyFields.add({
                    'name': entry.key.toString(),
                    'type': inferType(entry.value),
                    'desc': 'Inferred from file',
                  });
                }
              }
            } catch (e) {
              _errors.add('Invalid JSON file at line $lineNumber: $e');
            }
          }
        }
      } else if (tag == '@body-json') {
        isReadingBodyJson = true;
        bodyJsonBuffer.clear();
      }
    }

    flushEndpoint();

    if (_errors.isNotEmpty) {
      for (final error in _errors) {
        print('⚠️ $error');
      }
    }

    if (fileEndpoints.isNotEmpty) {
      _fileRegistry[filePath] = fileEndpoints;
      _generateSwaggerFile();
    } else if (_fileRegistry.containsKey(filePath)) {
      _fileRegistry.remove(filePath);
      _generateSwaggerFile();
    }
  }

  void _generateSwaggerFile() {
    final Map<String, dynamic> fullPaths = {};

    for (final fileMap in _fileRegistry.values) {
      for (final entry in fileMap.entries) {
        final path = entry.key;
        final methods = entry.value;
        if (fullPaths[path] == null) {
          fullPaths[path] = {};
        }
        (fullPaths[path] as Map).addAll(methods);
      }
    }

    _baseSpec['paths'] = fullPaths;

    // Add tags if any
    if (_tags.isNotEmpty) {
      _baseSpec['tags'] = _tags.map((t) => {"name": t}).toList();
    }

    final swaggerFile = File('frontend/web/froggy_docs.json');
    if (!swaggerFile.parent.existsSync()) {
      swaggerFile.parent.createSync(recursive: true);
    }

    swaggerFile.writeAsStringSync(
      JsonEncoder.withIndent('  ').convert(_baseSpec),
    );
    print(
      '🐸 FroggyDocs: Updated documentation. Total paths: ${fullPaths.length}',
    );
  }
}
