import 'dart:io';
import 'dart:convert';
import 'package:path/path.dart' as p;

class ParserEngine {
  static final Map<String, Map<String, dynamic>> _fileRegistry = {};

  static const Set<String> supportedExtensions = {
    '.dart',
    '.js',
    '.ts',
    '.jsx',
    '.tsx',
    '.py',
    '.go',
    '.rs',
    '.java',
    '.kt',
    '.scala',
    '.php',
    '.rb',
    '.cs',
    '.c',
    '.cpp',
    '.h',
    '.hpp',
  };

  static const Set<String> validMethods = {
    'get',
    'post',
    'put',
    'patch',
    'delete',
    'head',
    'options',
  };

  String _outputPath = 'frontend/web/froggy_docs.json';

  void setOutputPath(String path) {
    _outputPath = path;
  }

  String get outputPath => _outputPath;

  final Map<String, dynamic> _baseSpec = {
    "openapi": "3.0.0",
    "info": {
      "title": "FroggyDocs Generated API",
      "version": "1.0.0",
      "description": "Auto-generated by FroggyDocs",
    },
    "paths": {},
    "components": {
      "securitySchemes": {
        "bearerAuth": {
          "type": "http",
          "scheme": "bearer",
          "bearerFormat": "JWT",
        },
      },
    },
  };

  final List<String> _errors = [];
  final Set<String> _tags = {};

  String _getCommentPrefix(String filePath) {
    final ext = p.extension(filePath).toLowerCase();
    return switch (ext) {
      '.dart' => '//',
      '.js' || '.jsx' || '.ts' || '.tsx' => '//',
      '.py' || '.rb' => '#',
      '.go' ||
      '.rs' ||
      '.c' ||
      '.cpp' ||
      '.h' ||
      '.hpp' ||
      '.java' ||
      '.kt' ||
      '.scala' ||
      '.cs' => '//',
      '.php' => '//',
      _ => '//',
    };
  }

  bool _isCommentLine(String line, String prefix) {
    if (prefix == '//') {
      return line.trimLeft().startsWith('//');
    } else if (prefix == '#') {
      return line.trimLeft().startsWith('#');
    }
    return line.trimLeft().startsWith(prefix);
  }

  String _extractCommentText(String line, String prefix) {
    if (prefix == '//') {
      return line.replaceFirst(RegExp(r'^//\s*'), '').trim();
    } else if (prefix == '#') {
      return line.replaceFirst(RegExp(r'^#\s*'), '').trim();
    }
    return line.replaceFirst(RegExp(r'^$prefix\s*'), '').trim();
  }

  void removeFile(String filePath) {
    if (_fileRegistry.containsKey(filePath)) {
      _fileRegistry.remove(filePath);
      _generateSwaggerFile();
    }
  }

  dynamic _parseDefaultValue(String value, String? type) {
    switch (type?.toString().toLowerCase()) {
      case 'number':
      case 'integer':
      case 'int':
        return num.tryParse(value) ?? value;
      case 'boolean':
        return value.toLowerCase() == 'true';
      default:
        return value;
    }
  }

  void _attachResponseExample(
    String code,
    dynamic jsonData,
    Map<String, Map<String, dynamic>> responseSchemas,
  ) {
    final response = responseSchemas[code]!;
    if (!response.containsKey('content')) {
      response['content'] = <String, dynamic>{
        "application/json": <String, dynamic>{
          "schema": <String, dynamic>{"type": "object"},
        },
      };
    }
    final contentMap = response['content'] as Map;
    final appJsonMap = contentMap['application/json'] as Map;
    appJsonMap['example'] = jsonData;
  }

  void parseFile(String filePath) {
    _errors.clear();

    if (filePath.contains('frontend/') || filePath.contains('.dart_tool')) {
      return;
    }

    final file = File(filePath);
    if (!file.existsSync()) {
      removeFile(filePath);
      return;
    }

    final ext = p.extension(filePath).toLowerCase();
    if (!supportedExtensions.contains(ext)) {
      return;
    }

    final lines = file.readAsLinesSync();
    final commentPrefix = _getCommentPrefix(filePath);
    Map<String, dynamic> fileEndpoints = {};

    String? currentMethod;
    String? currentPath;
    String description = '';
    bool hasAuth = false;
    List<String> currentTags = [];
    List<Map<String, String>> requestBodyFields = [];
    List<Map<String, String>> requestFileFields = [];
    List<Map<String, dynamic>> queryParams = [];
    List<Map<String, dynamic>> headerParams = [];
    Map<String, Map<String, dynamic>> responseSchemas = {};
    String? pendingResponseCode;
    bool isReadingBodyJson = false;
    bool isReadingResponseJson = false;
    StringBuffer bodyJsonBuffer = StringBuffer();
    StringBuffer responseJsonBuffer = StringBuffer();
    int lineNumber = 0;

    String inferType(dynamic value) {
      if (value is String) return 'string';
      if (value is num) return 'number';
      if (value is bool) return 'boolean';
      if (value is List) return 'array';
      if (value is Map) return 'object';
      return 'string';
    }

    void flushEndpoint() {
      // Defensively flush any pending JSON buffers (handles end-of-file cases).
      if (isReadingBodyJson && bodyJsonBuffer.isNotEmpty) {
        isReadingBodyJson = false;
        try {
          final jsonData = jsonDecode(bodyJsonBuffer.toString());
          if (jsonData is Map) {
            for (final entry in jsonData.entries) {
              requestBodyFields.add({
                'name': entry.key.toString(),
                'type': inferType(entry.value),
                'desc': 'Inferred from JSON',
              });
            }
          }
        } catch (e) {
          _errors.add('Invalid JSON in @body-json at line $lineNumber: $e');
        }
        bodyJsonBuffer.clear();
      }

      if (isReadingResponseJson &&
          responseJsonBuffer.isNotEmpty &&
          pendingResponseCode != null) {
        isReadingResponseJson = false;
        try {
          final jsonData = jsonDecode(responseJsonBuffer.toString());
          _attachResponseExample(
            pendingResponseCode!,
            jsonData,
            responseSchemas,
          );
        } catch (e) {
          _errors
              .add('Invalid JSON in @response-json at line $lineNumber: $e');
        }
        responseJsonBuffer.clear();
      }

      if (currentMethod != null) {
        if (currentPath == null) {
          _errors.add('Endpoint defined without path at line $lineNumber');
          currentMethod = null;
          currentPath = null;
          description = '';
          hasAuth = false;
          currentTags.clear();
          requestBodyFields.clear();
          requestFileFields.clear();
          queryParams.clear();
          headerParams.clear();
          responseSchemas.clear();
          pendingResponseCode = null;
          bodyJsonBuffer.clear();
          responseJsonBuffer.clear();
          return;
        }

        if (!validMethods.contains(currentMethod!.toLowerCase())) {
          _errors.add(
            'Invalid HTTP method "$currentMethod" at line $lineNumber',
          );
          currentMethod = null;
          currentPath = null;
          description = '';
          hasAuth = false;
          currentTags.clear();
          requestBodyFields.clear();
          requestFileFields.clear();
          queryParams.clear();
          headerParams.clear();
          responseSchemas.clear();
          pendingResponseCode = null;
          bodyJsonBuffer.clear();
          responseJsonBuffer.clear();
          return;
        }

        final path = currentPath!;
        final method = currentMethod!.toLowerCase();

        if (fileEndpoints[path] == null) {
          fileEndpoints[path] = {};
        }

        final responses = <String, dynamic>{};
        if (responseSchemas.isEmpty) {
          responses['200'] = {"description": "Successful response"};
        } else {
          responses.addAll(responseSchemas);
        }

        Map<String, dynamic> endpointData = {
          "summary": description.isNotEmpty ? description : "No description",
          "responses": responses,
        };

        if (currentTags.isNotEmpty) {
          endpointData['tags'] = currentTags.toList();
        }

        if (hasAuth) {
          endpointData['security'] = [
            {"bearerAuth": []},
          ];
        }

        final parameters = <Map<String, dynamic>>[];
        for (var qp in queryParams) {
          final param = <String, dynamic>{
            "name": qp['name'],
            "in": "query",
            "description": qp['desc'] ?? '',
            "schema": <String, dynamic>{
              "type": (qp['type'] ?? 'string').toString().toLowerCase(),
            },
          };
          if (qp['default'] != null && (qp['default'] as String).isNotEmpty) {
            param['schema']['default'] = _parseDefaultValue(
              qp['default'] as String,
              qp['type'],
            );
          }
          parameters.add(param);
        }
        for (var hp in headerParams) {
          parameters.add({
            "name": hp['name'],
            "in": "header",
            "description": hp['desc'] ?? '',
            "schema": {
              "type": (hp['type'] ?? 'string').toString().toLowerCase(),
            },
          });
        }
        if (parameters.isNotEmpty) {
          endpointData['parameters'] = parameters;
        }

        if (requestBodyFields.isNotEmpty || requestFileFields.isNotEmpty) {
          final properties = <String, dynamic>{};
          for (var field in requestBodyFields) {
            final fieldName = field['name']!;
            properties[fieldName] = {
              "type": (field['type'] ?? 'string').toString().toLowerCase(),
              "description": field['desc'] ?? '',
            };
          }
          for (var field in requestFileFields) {
            final fieldName = field['name']!;
            properties[fieldName] = {
              "type": "string",
              "format": "binary",
              "description": field['desc'] ?? '',
            };
          }

          if (requestFileFields.isNotEmpty) {
            endpointData['requestBody'] = {
              "content": <String, dynamic>{
                "multipart/form-data": <String, dynamic>{
                  "schema": <String, dynamic>{
                    "type": "object",
                    "properties": properties,
                  },
                },
              },
            };
          } else {
            endpointData['requestBody'] = {
              "content": <String, dynamic>{
                "application/json": <String, dynamic>{
                  "schema": <String, dynamic>{
                    "type": "object",
                    "properties": properties,
                  },
                },
              },
            };
          }
        }

        fileEndpoints[path][method] = endpointData;
      }

      currentMethod = null;
      currentPath = null;
      description = '';
      hasAuth = false;
      currentTags.clear();
      requestBodyFields.clear();
      requestFileFields.clear();
      queryParams.clear();
      headerParams.clear();
      responseSchemas.clear();
      pendingResponseCode = null;
      bodyJsonBuffer.clear();
      responseJsonBuffer.clear();
    }

    for (final l in lines) {
      lineNumber++;
      final trimmed = l.trim();

      if (isReadingBodyJson) {
        if (!_isCommentLine(trimmed, commentPrefix)) {
          isReadingBodyJson = false;
          if (bodyJsonBuffer.isNotEmpty) {
            try {
              final jsonData = jsonDecode(bodyJsonBuffer.toString());
              if (jsonData is Map) {
                for (final entry in jsonData.entries) {
                  requestBodyFields.add({
                    'name': entry.key.toString(),
                    'type': inferType(entry.value),
                    'desc': 'Inferred from JSON',
                  });
                }
              }
            } catch (e) {
              _errors.add('Invalid JSON at line $lineNumber: $e');
            }
          }
          bodyJsonBuffer.clear();
        } else {
          final commentText = _extractCommentText(trimmed, commentPrefix);
          bodyJsonBuffer.write(commentText);
          continue;
        }
      }

      if (isReadingResponseJson) {
        if (!_isCommentLine(trimmed, commentPrefix)) {
          isReadingResponseJson = false;
          if (responseJsonBuffer.isNotEmpty && pendingResponseCode != null) {
            try {
              final jsonData = jsonDecode(responseJsonBuffer.toString());
              _attachResponseExample(
                pendingResponseCode!,
                jsonData,
                responseSchemas,
              );
            } catch (e) {
              _errors.add('Invalid response JSON at line $lineNumber: $e');
            }
          }
          responseJsonBuffer.clear();
        } else {
          final commentText = _extractCommentText(trimmed, commentPrefix);
          responseJsonBuffer.write(commentText);
          continue;
        }
      }

      if (!_isCommentLine(trimmed, commentPrefix)) {
        if (trimmed.isNotEmpty) {
          flushEndpoint();
        }
        continue;
      }

      final commentText = _extractCommentText(trimmed, commentPrefix);
      if (!commentText.startsWith('@')) {
        continue;
      }

      final parts = commentText.split(RegExp(r'\s+'));
      if (parts.isEmpty) continue;

      final tag = parts[0];

      if (tag == '@api') {
        flushEndpoint();
        if (parts.length >= 3) {
          currentMethod = parts[1].toUpperCase();
          currentPath = parts[2];
        } else {
          _errors.add('@api requires method and path at line $lineNumber');
        }
      } else if (tag == '@desc') {
        description = commentText.replaceFirst('@desc', '').trim();
      } else if (tag == '@auth') {
        hasAuth = true;
      } else if (tag == '@tag') {
        if (parts.length >= 2) {
          final tagName = parts.sublist(1).join(' ');
          if (!_tags.contains(tagName)) {
            _tags.add(tagName);
          }
          if (!currentTags.contains(tagName)) {
            currentTags.add(tagName);
          }
        }
      } else if (tag == '@body') {
        if (parts.length >= 3) {
          final fieldName = parts[1];
          final fieldType = parts[2];
          final fieldDesc = parts.length > 3 ? parts.sublist(3).join(' ') : '';
          requestBodyFields.add({
            'name': fieldName,
            'type': fieldType,
            'desc': fieldDesc,
          });
        } else {
          _errors.add(
            '@body requires field name and type at line $lineNumber',
          );
        }
      } else if (tag == '@file') {
        if (parts.length >= 3) {
          final fieldName = parts[1];
          final fileType = parts[2];
          final fieldDesc = parts.length > 3 ? parts.sublist(3).join(' ') : '';
          requestFileFields.add({
            'name': fieldName,
            'type': fileType,
            'desc': fieldDesc,
          });
        } else {
          _errors.add(
            '@file requires field name and type at line $lineNumber',
          );
        }
      } else if (tag == '@body-file') {
        if (parts.length >= 2) {
          final jsonFile = File(p.join(p.dirname(filePath), parts[1]));
          if (jsonFile.existsSync()) {
            try {
              final jsonData = jsonDecode(jsonFile.readAsStringSync());
              if (jsonData is Map) {
                for (final entry in jsonData.entries) {
                  requestBodyFields.add({
                    'name': entry.key.toString(),
                    'type': inferType(entry.value),
                    'desc': 'Inferred from file',
                  });
                }
              }
            } catch (e) {
              _errors.add('Invalid JSON file at line $lineNumber: $e');
            }
          }
        }
      } else if (tag == '@body-json') {
        isReadingBodyJson = true;
        bodyJsonBuffer.clear();
      } else if (tag == '@response') {
        if (parts.length >= 3) {
          pendingResponseCode = parts[1];
          final responseType = parts[2];
          final responseDesc =
              parts.length > 3 ? parts.sublist(3).join(' ') : '';
          final lowerType = responseType.toLowerCase();
          final schemaType = (lowerType == 'array') ? 'array' : 'object';
          responseSchemas[pendingResponseCode!] = {
            "description": responseDesc,
            "content": <String, dynamic>{
              "application/json": <String, dynamic>{
                "schema": <String, dynamic>{"type": schemaType},
              },
            },
          };
        } else {
          _errors.add(
            '@response requires status code and type at line $lineNumber',
          );
        }
      } else if (tag == '@response-json') {
        if (pendingResponseCode != null &&
            responseSchemas.containsKey(pendingResponseCode)) {
          final rest = commentText.replaceFirst('@response-json', '').trim();
          if (rest.isNotEmpty) {
            try {
              final jsonData = jsonDecode(rest);
              _attachResponseExample(
                pendingResponseCode!,
                jsonData,
                responseSchemas,
              );
            } catch (_) {
              isReadingResponseJson = true;
              responseJsonBuffer.clear();
              responseJsonBuffer.write(rest);
            }
          } else {
            isReadingResponseJson = true;
            responseJsonBuffer.clear();
          }
        }
      } else if (tag == '@query') {
        if (parts.length >= 3) {
          final name = parts[1];
          final type = parts[2];
          String desc = '';
          String? defaultValue;

          final rest = parts.length > 3 ? parts.sublist(3).join(' ') : '';
          final defaultMatch =
              RegExp(r'\(default:\s*(.+?)\)').firstMatch(rest);
          if (defaultMatch != null) {
            defaultValue = defaultMatch.group(1);
            desc = rest.replaceFirst(defaultMatch.group(0)!, '').trim();
          } else {
            desc = rest;
          }

          queryParams.add({
            'name': name,
            'type': type,
            'desc': desc,
            'default': defaultValue,
          });
        } else {
          _errors.add(
            '@query requires name and type at line $lineNumber',
          );
        }
      } else if (tag == '@header') {
        if (parts.length >= 3) {
          final name = parts[1];
          final type = parts[2];
          final desc = parts.length > 3 ? parts.sublist(3).join(' ') : '';
          headerParams.add({
            'name': name,
            'type': type,
            'desc': desc,
          });
        } else {
          _errors.add(
            '@header requires name and type at line $lineNumber',
          );
        }
      }
    }

    flushEndpoint();

    if (_errors.isNotEmpty) {
      for (final error in _errors) {
        print('⚠️  $error');
      }
    }

    if (fileEndpoints.isNotEmpty) {
      _fileRegistry[filePath] = fileEndpoints;
      _generateSwaggerFile();
    } else if (_fileRegistry.containsKey(filePath)) {
      _fileRegistry.remove(filePath);
      _generateSwaggerFile();
    }
  }

  void _generateSwaggerFile() {
    final Map<String, dynamic> fullPaths = {};

    for (final fileMap in _fileRegistry.values) {
      for (final entry in fileMap.entries) {
        final path = entry.key;
        final methods = entry.value;
        if (fullPaths[path] == null) {
          fullPaths[path] = {};
        }
        (fullPaths[path] as Map).addAll(methods);
      }
    }

    _baseSpec['paths'] = fullPaths;

    if (_tags.isNotEmpty) {
      _baseSpec['tags'] = _tags.map((t) => {"name": t}).toList();
    }

    final swaggerFile = File(_outputPath);
    if (!swaggerFile.parent.existsSync()) {
      swaggerFile.parent.createSync(recursive: true);
    }

    swaggerFile.writeAsStringSync(
      JsonEncoder.withIndent('  ').convert(_baseSpec),
    );
    print(
      '🐸 FroggyDocs: Updated documentation. Total paths: ${fullPaths.length}',
    );
  }

  Map<String, dynamic> generateSpec() {
    final Map<String, dynamic> fullPaths = {};
    for (final fileMap in _fileRegistry.values) {
      for (final entry in fileMap.entries) {
        final path = entry.key;
        final methods = entry.value;
        if (fullPaths[path] == null) {
          fullPaths[path] = {};
        }
        (fullPaths[path] as Map).addAll(methods);
      }
    }
    final spec = Map<String, dynamic>.from(_baseSpec);
    spec['paths'] = fullPaths;
    if (_tags.isNotEmpty) {
      spec['tags'] = _tags.map((t) => {"name": t}).toList();
    }
    return spec;
  }

  void clearRegistry() {
    _fileRegistry.clear();
    _tags.clear();
    _errors.clear();
  }

  int get pathCount {
    final Map<String, dynamic> fullPaths = {};
    for (final fileMap in _fileRegistry.values) {
      for (final entry in fileMap.entries) {
        final path = entry.key;
        final methods = entry.value;
        if (fullPaths[path] == null) {
          fullPaths[path] = {};
        }
        (fullPaths[path] as Map).addAll(methods);
      }
    }
    return fullPaths.length;
  }
}
